site_name: TWE Design System
repo_url: https://github.com/hackforla/internship-website-design-system
site_url: https://hackforla.github.io/internship-website-design-system/

nav:
  - Getting Started: index.md
  - Styles:
      - Typography: type-scale.md
  - Components:
    - Accordion: accordion.md
    - Buttons: buttons.md
    - Checkbox: checkbox.md
    - Input Fields: input-fields.md
    - Grid System: grid-system.md
    - Pagination: pagination.md
    - Radio Button: radio.md
    - Text Area: text-area.md
    - Toggles: toggles.md
    - Dropdown: dropdowns.md
   

plugins:
  - search:
      lang: en

theme:
  name: material
  font:
    text: roboto
  logo: Logo Flatten White.png
  features:
    # - navigation.expand
    - navigation.instant
    - navigation.path
    - content.code.copy
    - content.code.select
  palette:
    primary: white
    # accent: teal
  custom_dir: docs/overrides

extra_css:
  - https://fonts.googleapis.com/icon?family=Material+Icons+Outlined
  - dist/main.css
  - stylesheets/extra.css
  - dist/material-icons.css
  # - /bootstrap/css/bootstrap.min.css

extra_javascript:
  - javascript/extra.js
  - javascript/pagination.js
  - javascript/dropdown.js
  # - javascript/bootstrap.min.js
  # - https://code.jquery.com/jquery-1.12.4.min.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
